package edu.pitt.cs;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Get Reset link href attribute
    WebElement resetLink = driver.findElement(By.linkText("Reset"));
    String href = resetLink.getAttribute("href");
    // Assert href is /reset (or ends with /reset for full URLs)
    assertTrue(href.equals("/reset") || href.endsWith("/reset"));
  }
  @Test
  public void tEST2RESET() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Precondition: Set all cats to rented
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    // Click Reset link
    driver.findElement(By.linkText("Reset")).click();
    // Verify first cat is available
    assertThat(driver.findElement(By.id("cat-id1")).getText(), is("ID 1. Jennyanydots"));
    // Verify second cat is available
    assertThat(driver.findElement(By.id("cat-id2")).getText(), is("ID 2. Old Deuteronomy"));
    // Verify third cat is available
    assertThat(driver.findElement(By.id("cat-id3")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Catalog link
    driver.findElement(By.linkText("Catalog")).click();
    // Execute script to verify second image source
    vars.put("srcCheck", js.executeScript("return document.querySelectorAll(\'ol li img\')[1].getAttribute(\'src\').endsWith(\'/images/cat2.jpg\')"));
    // Assert the check returned true
    assertEquals(vars.get("srcCheck").toString(), "true");
  }
  @Test
  public void tEST4LISTING() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Catalog link
    driver.findElement(By.linkText("Catalog")).click();
    // Verify there are 3 list items
    {
      List<WebElement> elements = driver.findElements(By.xpath("//ol/li[3]"));
      assert(elements.size() > 0);
    }
    // Verify no 4th item exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//ol/li[4]"));
      assert(elements.size() == 0);
    }
    // Verify third item text
    assertThat(driver.findElement(By.xpath("//div/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST5RENTACAT() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Verify Rent button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Rent\']"));
      assert(elements.size() > 0);
    }
    // Verify Return button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Return\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Enter cat ID 1
    driver.findElement(By.id("rentID")).sendKeys("1");
    // Click Rent button
    driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
    // Verify first cat is rented
    assertThat(driver.findElement(By.xpath("//div/ul/li[1]")).getText(), is("Rented out"));
    // Verify second cat is available
    assertThat(driver.findElement(By.xpath("//div/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    // Verify third cat is available
    assertThat(driver.findElement(By.xpath("//div/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    // Verify Success message
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST7RETURN() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Precondition: Set cat 2 to rented
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    // Click Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Enter cat ID 2
    driver.findElement(By.id("returnID")).sendKeys("2");
    // Click Return button
    driver.findElement(By.xpath("//button[text()=\'Return\']")).click();
    // Verify first cat is available
    assertThat(driver.findElement(By.id("cat-id1")).getText(), is("ID 1. Jennyanydots"));
    // Verify second cat is available
    assertThat(driver.findElement(By.id("cat-id2")).getText(), is("ID 2. Old Deuteronomy"));
    // Verify third cat is available
    assertThat(driver.findElement(By.id("cat-id3")).getText(), is("ID 3. Mistoffelees"));
    // Verify Success message
    assertThat(driver.findElement(By.id("returnResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST8FEEDACAT() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Feed-A-Cat link
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // Verify Feed button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Feed\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Feed-A-Cat link
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // Enter 6 catnips
    driver.findElement(By.id("catnips")).sendKeys("6");
    // Click Feed button
    driver.findElement(By.xpath("//button[text()=\'Feed\']")).click();
    // Wait for Nom text to appear
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")));
    }
    // Verify Nom message
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("Nom, nom, nom."));
  }
  @Test
  public void tEST10GREETACAT() {
    // Test Fixture: Open URL
    driver.get("http://localhost:8080");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Click Greet-A-Cat link
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    // Verify three Meows appear
    assertThat(driver.findElement(By.id("greeting")).getText(), is("Meow!Meow!Meow!"));
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    // Test Fixture: Open URL with cat name
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    // Test Fixture: Reset cookies
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    // Verify greeting with name appears
    assertThat(driver.findElement(By.id("greeting")).getText(), is("Meow! from Jennyanydots."));
  }
}
